class tc_chi_d_write_partial_smoke extends vip_chi_base_test;

  `uvm_component_utils(tc_chi_d_write_partial_smoke)

  // ---------------------------------------------------------------------------
  // Constructor
  // ---------------------------------------------------------------------------
  function new(input string name, input uvm_component parent = null);

    super.new(name, parent);

  endfunction

  // ---------------------------------------------------------------------------
  // Compute the expected partial-write image using the generated byte enables.
  // ---------------------------------------------------------------------------
  protected function item_t::data_t expected_partial_data(
    input item_t::data_t write_data,
    input item_t::be_t   write_be
  );

    item_t::data_t result;

    result = '0;
    for (int byte_index = 0; byte_index < CHI_D_CFG_C.DATA_BYTES_P; byte_index++) begin
      if (write_be[byte_index]) begin
        result[8 * byte_index +: 8] = write_data[8 * byte_index +: 8];
      end
    end

    return result;
  endfunction

  // ---------------------------------------------------------------------------
  // Verify masked writeback behavior through the autonomous SN-F backing store.
  // ---------------------------------------------------------------------------
  task run_phase(input uvm_phase phase);

    item_t::data_t                  write_data_q[$];
    item_t::be_t                    write_be_q[$];
    item_t                          req_items[$];
    item_t                          dat_items[$];
    item_t                          write_responses[$];
    item_t                          read_responses[$];
    item_t::data_t                  expected_data;

    phase.raise_objection(this);

    write_data_q.push_back(item_t::data_t'(128'h0011_2233_4455_6677_8899_AABB_CCDD_EEFF));
    write_be_q.push_back(item_t::be_t'(16'b1111_0000_0011_0101));
    expected_data = this.expected_partial_data(write_data_q[0], write_be_q[0]);

    super.rni0_wr_seq.reset();
    super.rni0_wr_seq.set_initial_addr(WRITE_ADDR_C);
    super.rni0_wr_seq.set_size(3'd4);
    super.rni0_wr_seq.set_allow_retry(1'b0);
    super.rni0_wr_seq.set_data(write_data_q);
    super.rni0_wr_seq.set_be(write_be_q);
    super.rni0_wr_seq.set_get_response(1'b1);
    super.rni0_wr_seq.set_verbose(1'b0);
    super.rni0_wr_seq.start(super.v_sqr.rni_sequencer);

    super.rni0_rd_seq.reset();
    super.rni0_rd_seq.set_requests(1);
    super.rni0_rd_seq.set_initial_addr(WRITE_ADDR_C);
    super.rni0_rd_seq.set_size(3'd4);
    super.rni0_rd_seq.set_allow_retry(1'b0);
    super.rni0_rd_seq.set_get_response(1'b1);
    super.rni0_rd_seq.set_verbose(1'b0);
    super.rni0_rd_seq.start(super.v_sqr.rni_sequencer);

    write_responses = super.rni0_wr_seq.get_responses();
    read_responses  = super.rni0_rd_seq.get_responses();

    if (write_responses.size() != 1) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Expected 1 write response, got %0d",
        super.tc_name, write_responses.size()))
    end

    if (read_responses.size() != 1) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Expected 1 read response, got %0d",
        super.tc_name, read_responses.size()))
    end

    repeat (2) begin
      item_t req_item;
      super.tb_env.rni_req_fifo.get(req_item);
      req_items.push_back(req_item);
    end

    repeat (2) begin
      item_t dat_item;
      super.tb_env.rni_dat_fifo.get(dat_item);
      dat_items.push_back(dat_item);
    end

    if (req_items[0].opcode != item_t::req_opcode_t'(VIP_CHI_REQ_WRITE_NO_SNP_PTL_C)) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] First request was not WriteNoSnpPtl: 0x%0h",
        super.tc_name, req_items[0].opcode))
    end

    if (req_items[1].opcode != item_t::req_opcode_t'(VIP_CHI_REQ_READ_NO_SNP_C)) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Second request was not ReadNoSnp: 0x%0h",
        super.tc_name, req_items[1].opcode))
    end

    if ((req_items[0].addr != WRITE_ADDR_C) || (req_items[1].addr != WRITE_ADDR_C)) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Partial-write/read address mismatch 0x%0h 0x%0h",
        super.tc_name, req_items[0].addr, req_items[1].addr))
    end

    if (dat_items[0].role != VIP_CHI_ROLE_RNI_E) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] First DAT item role was not RN-I: %0d",
        super.tc_name, dat_items[0].role))
    end

    if (dat_items[1].role != VIP_CHI_ROLE_SNF_E) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Second DAT item role was not SN-F: %0d",
        super.tc_name, dat_items[1].role))
    end

    if ((dat_items[0].data.size() != 1) || (dat_items[1].data.size() != 1)) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Expected one write DAT beat and one read DAT beat, got %0d and %0d",
        super.tc_name, dat_items[0].data.size(), dat_items[1].data.size()))
    end

    if (dat_items[0].be[0] != write_be_q[0]) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Write DAT BE mismatch 0x%0h vs 0x%0h",
        super.tc_name, dat_items[0].be[0], write_be_q[0]))
    end

    if (dat_items[0].data[0] != write_data_q[0]) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Write DAT payload mismatch 0x%0h vs 0x%0h",
        super.tc_name, dat_items[0].data[0], write_data_q[0]))
    end

    if (write_responses[0].rsp_opcode != item_t::rsp_opcode_t'(VIP_CHI_RSP_COMP_DBID_RESP_C)) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Write response carried wrong opcode 0x%0h",
        super.tc_name, write_responses[0].rsp_opcode))
    end

    if (read_responses[0].dat_opcode != item_t::dat_opcode_t'(VIP_CHI_DAT_COMP_DATA_C)) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Read response carried wrong DAT opcode 0x%0h",
        super.tc_name, read_responses[0].dat_opcode))
    end

    if (dat_items[1].data[0] != expected_data) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Read DAT payload mismatch 0x%0h vs expected 0x%0h",
        super.tc_name, dat_items[1].data[0], expected_data))
    end

    if (read_responses[0].data[0] != expected_data) begin
      `uvm_fatal(get_name(), $sformatf(
        "FATAL [%s] Read response payload mismatch 0x%0h vs expected 0x%0h",
        super.tc_name, read_responses[0].data[0], expected_data))
    end

    phase.drop_objection(this);
  endtask
endclass